### ISSUE TITLE
[enhancement] Implementazione documentazione in maniera strutturata

### ISSUE THREAD

**Issue by h3r0cybersec** [niktorthenat/lungo#2]
Ciao @niktorthenat , ho visto che stai lavorando per implementare il classico "aiuto in linea" a livello di codice, in modo che sia possibile avere una reference sul linguaggio nell'editor stesso; operazione comune in tutti gli editor di un certo livello 😄.
Avrei qualche suggerimento per strutturare meglio il codice:

- perchè non implementare la documentazione come finestra separata avviabile dall'editor? Sarebbe una finestra semplice con due frame uno a sinistra che mostra tutte le categorie/opzioni e uno a destra che mostra il contenuto della catergoria/opzione nel momento in cui si fà click sulla categoria/opzione.
- perchè in vece di scrivere la documentazione come testo semplice, non accorparla in una directory **doc** con dentro ogni **pagina** della documentazione scritta in **markdown** ? 

### Prima domanda
Giusto per darti un idea di quello che intendo qualcosa tipo la classica finestra di windows con l'help sulle funzionalità: [Help](https://www.google.com/search?q=help+window&sxsrf=ALeKk00wDnfyeaVHPlXW902C7XyLG9ozJw:1613649326011&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi-r_mWsPPuAhWXraQKHe3hBNEQ_AUoAXoECBUQAw&biw=1280&bih=891#imgrc=sMYpogx-bbX5rM)

### Seconda domanda
 Intendo una struttura di questo tipo:

doc/
 |____ stringhe/
 |_____________ stampa
|_____ web/
|__________ ....

In questo modo la struttura del documento nel pannello di sinistra viene creata leggendo la struttura delle directory mettendo tutto in una TreeView, mentre il pannello di destra viene creato popolando una ( magari ) Textarea in solo lettura, al click su una funzionalità di sinistra, interpretando il file **markdown**.

**Comment by niktorthenat** [comment]
Non posso che darti perfettamente ragione sull'implementare l'help come hai dettagliatamente spiegato. 
Considera che Lungo lo sto pensando e riscrivendo ogni volta da zero, da alcuni anni, e ogni volta mi interrompo e lo riscrivo, sia perchè non trova interesse negli utenti, sia perchè miglioro sempre "il cuore" del sistema di programmazione.
Per questo motivo non ha un help "moderno" come da te rilevato, proprio perchè stavo giocherellando nuovamente con il codice per realizzare "Lungo", e come per magia, gli utenti hanno iniziato ad interessarsi a questa idea, e così mi sono trovato impreparato.
Dopo aver letto ieri questo tuo quesito, ho provato a vedere di realizzare un Wiki, ma mi sono bloccato per sistemare il codice di Lungo, che aveva cose urgenti da implementare, e così ho capito che non è il momento di generare l'help.
Procederò prima con la pubblicazione di video tutorial, per le singole istruzioni, perchè catturano di più l'interesse degli utenti, e se andrà bene, seguire al volo il tuo prezioso consiglio, usando il metodo della documentazione scritta in **markdown**, che non avevo mai usato prima. Credo che la userò con un editor a parte a cui si collegherà Lungo e non implementata dentro il linguaggio, perchè richiederebbe maggiore sforzo...

**Comment by h3r0cybersec** [comment]
@niktorthenat  se per te non è un problema mi piacerebbe davvero aiutarti con questo progetto il mio obiettivo e vederlo arrivare un giorno nelle scuole, così come altri progetti che facilitano la programmazione per quelle persone che stanno muovendo i primi passi in questo mondo (esempio lampante scratchpad 😄). 
Penso ci siano tutte le carte in regola per arrivare a qualcosa di fatto davvero molto bene e ci credo realmente.  Posso occuparmi io della parte della documentazione e mandarti una bozza non appena arrivato a qualcosa di più o meno carino. 
So bene che con il tuo canale youtube da mandare avanti è abbastanza difficile trovare il tempo per dedicarti anche a questa parte e si ho notato anche io che al momento hai un bel calo di visualizzazioni. Bisogna trovare un modo per rendere **Lungo** attraente anche per tutti gli utenti che ti seguono e hanno anche determinate competenze.
